 /*Mostrar campus con director, dirección y carreras*/

SELECT 
  c.nombre AS campus,
  c.directivo,
  c.direccion,
  GROUP_CONCAT(ca.nombre SEPARATOR ', ') AS carreras
FROM campus c
JOIN Oferta o ON c.idCampus = o.idCampus
JOIN carrera ca ON o.idCarrera = ca.idCarrera
GROUP BY c.idCampus;
+--------------------------------------------------------+--------------------------------------+------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| campus                                                 | directivo                            | direccion                                                                                | carreras                                                                                                                                                                                                                                                                                                                                                                                                                  |
+--------------------------------------------------------+--------------------------------------+------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Instituto Tecnologico de Comitancillo                  | Mtra. Carina Peña Cabrera            | Carretera Ixtaltepec - Comitancillo km 7.5, 70750 San Pedro Comitancillo, Oax.           | Administración y gestión, Ingeniería en Tecnologías de la Información y Comunicaciones, Ingeniería en Manufactura y Construcción, Ingeniería en Agronomía, Administración de empresas, Ingeniería en Informática, Ingeniería en Industrias Alimentarias, Ingeniería en Producción y Explotación Agrícola y Ganadera, Ingeniería en Gestión Empresarial                                                                    |
| Instituto Tecnologico de Istmo                         | Ing. Juan José Rementería Orozco     | Panamericana 821, 2da., 70000 Juchitán de Zaragoza, Oax.                                 | Ingeniería Civil, Ingeniería Eléctrica, Ingeniería Electromecánica, Ingeniería Industrial, Ingeniería Mecánica, Ingeniería Mecatrónica, Ingeniería en Sistemas Computacionales, Ingeniería en Informática, Ingeniería en Gestión Empresarial, Licenciatura en Arquitectura, Contador Público                                                                                                                              |
| Instituto Tecnologico de La Cuenca del Papaloapan      | Ing. Brígido Castrejón Sánchez       | Av. Tecnológico No.21 San Bartolo, Tuxtepec, Oaxaca                                      | Licenciatura en Biología, Administración y gestión, Licenciatura en Filosofía, Ingeniería en Agronomía                                                                                                                                                                                                                                                                                                                    |
| Instituto Tecnologico de Oaxaca                        | M.C Silvia Santiago Cruz             | Avenida Ing. Víctor Bravo Ahuja No. 125 Esquina Calzada Tecnológico, C.P. 68030          | Administración y gestión, Contador Público, Ingeniería Civil, Ingeniería Eléctrica, Ingeniería Electrónica, Ingeniería Industrial, Ingeniería Mecánica, Ingeniería Química, Ingeniería en Sistemas Computacionales, Ingeniería en Gestión Empresarial                                                                                                                                                                     |
| Instituto Tecnologico de Pinotepa                      | Arturo de la Rosa Galindo            | 71600 Santiago Pinotepa Nacional, Oax.                                                   | Contador Público, Ingeniería Industrial, Ingeniería en Agronomía, Administración y gestión, Ingeniería en Gestión Empresarial, Ingeniería en Sistemas Computacionales, Maestría en Producción Agroalimentaria                                                                                                                                                                                                             |
| Instituto Tecnologico de Pochutla                      | Jorge Armando Hernandez Valencia     | Km. 5.35 Carretera, Puerto Angel - Oaxaca, 70902 San Pedro Pochutla, Oax.                | Administración y gestión, Ingeniería Civil, Ingeniería Electromecánica, Ingeniería en Gestión Empresarial, Ingeniería en Sistemas Computacionales, Ingeniería en Industrias Alimentarias                                                                                                                                                                                                                                  |
| Instituto Tecnologico de Salina Cruz                   |  Ing. Carlos Alberto Mateos Mendoza  | Carretera a San Antonio Monterrey Km 1.7, Granadino, 70701 Salina Cruz, Oax.             | Ingeniería en Acuicultura, Ingeniería Mecánica, Ingeniería Electrónica, Ingeniería en Gestión Empresarial, Ingeniería en Tecnologías de la Información y Comunicaciones                                                                                                                                                                                                                                                   |
| Instituto Tecnologico de Tlaxiaco                      | Mtro. Amado Santos Santiago          | Km 2.5, Blvd. Tecnológico, Llano Yosove, 69800 Tlaxco, Oax.                              | Administración y gestión, Licenciatura en Arquitectura, Ingeniería Civil, Ingeniería Industrial, Ingeniería Mecatrónica, Ingeniería en Sistemas Computacionales, Ingeniería en Gestión Empresarial                                                                                                                                                                                                                        |
| Instituto Tecnologico de Tuxtepec                      | M. C. Santiago Enrique Torres Loyo   | Avenida Dr, Víctor Bravo Ahuja S/N, 5 de Mayo, 68350 San Juan Bautista Tuxtepec, Oax.    | Administración y gestión, Contador Público, Ingeniería en Bioquímica, Ingeniería Civil, Ingeniería Electrónica, Ingeniería Electromecánica, Ingeniería en Gestión Empresarial, Ingeniería en Informática, Ingeniería en Sistemas Computacionales                                                                                                                                                                          |
| Instituto Tecnologico de Valle de Etla                 | Mtro. Adrián Martínez Vargas         | Abasolo S/N, Barrio del Agua Buena, 68230 Oax.                                           | Administración y gestión, Ingeniería Civil, Ingeniería en Desarrollo Comunitario, Ingeniería en Energías Renovables, Ingeniería Ferroviaria, Ingeniería en Gestión Empresarial, Ingeniería Industrial                                                                                                                                                                                                                     |
| Instituto Tecnologico de Valle de Oaxaca               | M.C. Sergio Fernando Garibay Armenta | Carretera al ITAO s/n, Col. San Jesús Nazareno CP 71233, Santa Cruz Xoxocotlán, Oaxaca   | Ingeniería Forestal, Ingeniería en Tecnologías de la Información y Comunicaciones, Ingeniería Ambiental, Ingeniería en Informática, Licenciatura en Biología, Ingeniería en Agronomía, Ingeniería en Ciencia de Datos, Ingeniería en Gestión Empresarial, Maestría en Ciencias en Biología, Maestría en Ciencias Productividad de Agroecosistemas, Doctorado en Ciencias Productividad de Agroecosistemas                 |
| Instituto Tecnologico Superior de San Miguel el Grande | Lic. Saul Claudio Aparicio Aparicio  | Carretera a la Comunidad de Morelos s/n km.1.2, San Miguel el Grande, Tlaxiaco, Oaxaca   | Administración y gestión, Ingeniería en Desarrollo Comunitario, Ingeniería en Innovación Agrícola Sustentable, Ingeniería en Tecnologías de la Información y Comunicaciones, Ingeniería Forestal                                                                                                                                                                                                                          |
| Instituto Tecnologico Superior de Teposcolula          |  Dr. Misael Cruz Bautista            |  Av tecnologico s/n, Paraje el alarcon, 69500 San Pedro y San Pablo Teposcolula, Oax     | Licenciatura en Gastronomía, Administración y gestión, Ingeniería en Desarrollo Comunitario, Ingeniería en Logística, Ingeniería en Sistemas Computacionales                                                                                                                                                                                                                                                              |
+--------------------------------------------------------+--------------------------------------+------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

/*Listar todas las carreras y los campus donde se imparten*/
